# Generated by Django 3.2.9 on 2022-10-26 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0004_auto_20221026_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resuser',
            name='email',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='resuser',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
