# Generated by Django 3.2.9 on 2022-10-27 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0006_alter_feedback_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='total_feedback',
        ),
    ]
