# Generated by Django 3.2.9 on 2022-10-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0007_remove_feature_total_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='font_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
